[platformio]
default_envs = esp32dev

[env]
monitor_speed = 115200
build_flags =
  -std=gnu++17
  -DAIRKVM_FW_VERSION=\"dev\"

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 115200
build_unflags =
  -std=gnu++11
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.3

[env:native]
platform = native
test_framework = unity
test_build_src = true
build_src_filter =
  +<protocol.cpp>
build_flags =
  -std=gnu++17
